<?php

namespace Microscrap\Bindings\AppKit\Enums;

/** AppKit `NSApplicationPresentationOptions` (NSUInteger). Pass `::CASE->value` into ns_* ints. */
enum ApplicationPresentationOptions: int
{
    case APPLICATION_PRESENTATION_DEFAULT = 0;
    case APPLICATION_PRESENTATION_AUTO_HIDE_DOCK = 1;
    case APPLICATION_PRESENTATION_HIDE_DOCK = 2;
    case APPLICATION_PRESENTATION_AUTO_HIDE_MENU_BAR = 3;
    case APPLICATION_PRESENTATION_HIDE_MENU_BAR = 4;
    case APPLICATION_PRESENTATION_DISABLE_APPLE_MENU = 5;
    case APPLICATION_PRESENTATION_DISABLE_PROCESS_SWITCHING = 6;
    case APPLICATION_PRESENTATION_DISABLE_FORCE_QUIT = 7;
    case APPLICATION_PRESENTATION_DISABLE_SESSION_TERMINATION = 8;
    case APPLICATION_PRESENTATION_DISABLE_HIDE_APPLICATION = 9;
    case APPLICATION_PRESENTATION_DISABLE_MENU_BAR_TRANSPARENCY = 10;
    case APPLICATION_PRESENTATION_FULL_SCREEN = 11;
    case APPLICATION_PRESENTATION_AUTO_HIDE_TOOLBAR = 12;
    case APPLICATION_PRESENTATION_DISABLE_CURSOR_LOCATION_ASSISTANCE = 13;
}
