<?php

namespace Microscrap\Bindings\AppKit\Enums;

/** AppKit `NSLayoutFormatOptions` (NSUInteger). Pass `::CASE->value` into ns_* ints. */
enum LayoutFormatOptions: int
{
    case LAYOUT_FORMAT_ALIGN_ALL_LEFT = 0;
    case LAYOUT_FORMAT_ALIGN_ALL_RIGHT = 1;
    case LAYOUT_FORMAT_ALIGN_ALL_TOP = 2;
    case LAYOUT_FORMAT_ALIGN_ALL_BOTTOM = 3;
    case LAYOUT_FORMAT_ALIGN_ALL_LEADING = 4;
    case LAYOUT_FORMAT_ALIGN_ALL_TRAILING = 5;
    case LAYOUT_FORMAT_ALIGN_ALL_CENTER_X = 6;
    case LAYOUT_FORMAT_ALIGN_ALL_CENTER_Y = 7;
    case LAYOUT_FORMAT_ALIGN_ALL_LAST_BASELINE = 8;
    case LAYOUT_FORMAT_ALIGN_ALL_FIRST_BASELINE = 9;
    case LAYOUT_FORMAT_ALIGN_ALL_BASELINE = 10;
    case LAYOUT_FORMAT_ALIGNMENT_MASK = 12;
    case LAYOUT_FORMAT_DIRECTION_LEADING_TO_TRAILING = 13;
    case LAYOUT_FORMAT_DIRECTION_LEFT_TO_RIGHT = 65536;
    case LAYOUT_FORMAT_DIRECTION_RIGHT_TO_LEFT = 15;
    case LAYOUT_FORMAT_DIRECTION_MASK = 16;
    case LAYOUT_FORMAT_SPACING_EDGE_TO_EDGE = 17;
    case LAYOUT_FORMAT_SPACING_BASELINE_TO_BASELINE = 524288;
    case LAYOUT_FORMAT_SPACING_MASK = 19;
}
